#!/bin/bash
# This script was autogenerated by generateExperiment.py script inside the myrtle repo.
cd ..;
export experimentDir=/repo/16x16x16;
#bash myrtle-experiments/many_gemms.sh ./16x16x16/16x16x16wm-n-k_ss_c_rem_div_ana_pruned.csv no no extract;
python myrtle-experiments/combineTilingSchemeDataIntoSingleCSV.py ./16x16x16/16x16x16wm-n-k_ss_c_rem_div_ana_pruned.csv $experimentDir;
cd 16x16x16;
