#!/bin/bash
# This script was autogenerated by generateExperiment.py script inside the myrtle repo.
cd ..;
export experimentDir=/repo/16x16x16;
export WALL_TIMEOUT=0;
bash myrtle-experiments/many_gemms.sh ./16x16x16/16x16x16wm-n-k_ss_c_rem_div_ana_pruned.csv check run no no > ./16x16x16/run-16x16x16wm-n-k.txt;
cd 16x16x16;
