#!/bin/bash
# This script was autogenerated by topTenFromMNK.py script inside the myrtle repo.
cd ..;
bash many_gemms.sh ./top10/384x384x384wm-n-k_searchSpace_L1_top_10.csv check run no no > ./top10/run-384x384x384wm-n-k_searchSpace.txt;
bash many_gemms.sh ./top10/96x384x384wm-n-k_searchSpace_L1_top_10.csv check run no no > ./top10/run-96x384x384wm-n-k_searchSpace.txt;
bash many_gemms.sh ./top10/128x128x512wm-n-k_searchSpace_L1_top_10.csv check run no no > ./top10/run-128x128x512wm-n-k_searchSpace.txt;
cd top10;
