import sys
import pandas as pd
import numpy as np
import json
import os.path
print("\n\t\textractKernelTimeFromJsons.py: ATTN: only many_gemms.sh should call this script.")

# python combineKernelTimesIntoSingleCSV.py "256x256x256wm-n-k_searchSpace_c_analyzed-myrtle-sflt-ranking-top5.csv"
# python combineKernelTimesIntoSingleCSV.py "256x256x256wm-n-k_searchSpace_c_analyzed.csv"

def main():
    if len(sys.argv) !=2:
        print("\t",end='')
        print(f"USAGE: Requires search space CSV file name as input.")
    else:
        f=sys.argv[1]
        print(f)
        df = pd.read_csv(f)
        
        # TODO: remove hardcoding
        logsRootPath="sw/kernels/blas/gemm"
        # generate file path to each tiling scheme's csv file (generated by extractKernelTimeFromJsons.py)
        # collect the csv file paths into a list of paths
        all_files = df.apply(lambda x : f'{logsRootPath}/{x["FakeNN JSON Name"]}/logs/{x["FakeNN JSON Name"]}.csv', axis=1).to_list()
        # take the first csv file in the list, and merge the rest of the csv files into that first one
        original = all_files[0]
        rest = all_files[1:]
        orig = pd.read_csv(original)
        # super clunkly way to get rid of the "unamed" first column
        # orig = orig[["core0","core1","core2","core3","core4","core5","core6","core7","dma","Kernel Time","FakeNN JSON Name"]]
        # print(orig[["core0","core1","core2","core3","core4","core5","core6","core7","dma","Kernel Time","FakeNN JSON Name"]])
        for r in rest:
            if not os.path.exists(r):
                print(f"Skipping {r}")
            else:
                rdf = pd.read_csv(r)
                rdf = rdf[["core0","core1","core2","core3","core4","core5","core6","core7","dma","Kernel Time","FakeNN JSON Name"]]
                #orig = orig.merge(rdf,how='outer')
                orig=pd.concat([orig,rdf])
                # print(rdf)
                # print(rdf.iloc[0])
        # file name for combined data is the original csv name with "results" appended to the end
        outputFile = f'{f[:-4]}-results.csv'
        df = df.merge(orig, how='outer')
        df = df.drop("Unnamed: 0",axis=1)
        print(outputFile)
        df.to_csv(outputFile)
       

if __name__ == "__main__":
    main()

   
    