import sys
import pandas as pd
import numpy as np
import json
import os.path
print("\n\t\tcombineKernelTimesIntoSingleCSV.py: ATTN: only many_gemms.sh should call this script.")

# python combineKernelTimesIntoSingleCSV.py "256x256x256wm-n-k_searchSpace_c_analyzed-myrtle-sflt-ranking-top5.csv"
# python combineKernelTimesIntoSingleCSV.py "256x256x256wm-n-k_searchSpace_c_analyzed.csv"

def main():
    if len(sys.argv) !=3:
        print("\t",end='')
        print("USAGE: Requires search space CSV file name and kernel directory as input.")
    else:
        f=sys.argv[1]
        print(f)
        df = pd.read_csv(f)
        logsRootPath=f"{sys.argv[2]}"
        # generate file path to each tiling scheme's csv file (generated by extractKernelTimeFromJsons.py)
        # collect the csv file paths into a list of paths
        all_files = df.apply(lambda x : f'{logsRootPath}/{x["FakeNN JSON Name"]}/build/logs/{x["FakeNN JSON Name"]}.csv', axis=1).to_list()
        # take the first csv file in the list, and merge the rest of the csv files into that first one
        original = all_files[0]
        rest = all_files[1:]
        orig = pd.read_csv(original)
        for r in rest:
            if not os.path.exists(r):
                print(f"Skipping {r}")
            else:
                rdf = pd.read_csv(r)
                rdf = rdf[["core0","core1","core2","core3","core4","core5","core6","core7","dma","Kernel Time","FakeNN JSON Name"]]
                #orig = orig.merge(rdf,how='outer')
                orig=pd.concat([orig,rdf])
                # print(rdf)
                # print(rdf.iloc[0])
        # file name for combined data is the original csv name with "results" appended to the end
        outputFile = f'{f[:-4]}-results.csv'
        df = df[["FakeNN JSON Name"]] # only take the unique id from the search space
        df = df.merge(orig, how='outer')
        print(outputFile)
        df.to_csv(outputFile,index=False)
        # if there are rows without timing information, emit a second file with only the timed rows
        if df["dma"].isnull().any() :
            print("some of the rows do not contain timing information")
            unskipped = df[df["dma"].notnull()] # df[df['col'].notnull()] ]
            outputFile = f'{f[:-4]}-results-unskipped.csv'
            unskipped.to_csv(outputFile,index=False)
            print(outputFile)
            skipped = df[df["dma"].isnull()]
            outputFile = f'{f[:-4]}-results-skipper.csv'
            skipped.to_csv(outputFile,index=False)
            print(outputFile)
       

if __name__ == "__main__":
    main()

   
    