#!/bin/bash
# This script was autogenerated by topTenFromMNK.py script inside the myrtle repo.
cd ..;
bash many_gemms.sh ./8x16x16/8x16x16wm-n-k_searchSpace_searchSpace_L1_top_10.csv no no no extract;
python combineKernelTimesIntoSingleCSV.py ./8x16x16/8x16x16wm-n-k_searchSpace_searchSpace_L1_top_10.csv;
cd 8x16x16;
