#!/bin/bash
# This script was autogenerated by topTenFromMNK.py script inside the myrtle repo.
cd ..;
bash many_gemms.sh ./8x16x16/8x16x16wm-n-k_searchSpace_searchSpace_L1_top_10.csv check run no no > ./8x16x16/run-8x16x16wm-n-k_searchSpace.txt;
cp sw/kernels/blas/matmul_padded/8x16x16w8-16-8/verify-output.txt 8x16x16/verify-output.txt
cp sw/kernels/blas/matmul_padded/8x16x16w8-16-8/output.txt 8x16x16/output.txt
cp sw/kernels/blas/matmul_padded/8x16x16w8-16-8/params.json 8x16x16/params.json
cd 8x16x16;
