#!/bin/bash
# This script was autogenerated by topTenFromMNK.py script inside the myrtle repo.
cd ..;
bash many_gemms.sh ./8x16x16w8-16-16up8-8-5/8x16x16wm-n-k_searchSpace_searchSpace_L1_top_10.csv compile no no no > ./8x16x16w8-16-16up8-8-5/compile-8x16x16wm-n-k_searchSpace.txt;
cd 8x16x16w8-16-16up8-8-5;
